# you must include the "" marks around your input unless it is true/false or a ["list"]
[settings]
  # whitelist is case-sensitive
  whitelist = ["TslGame.exe", "csgo.exe", "mumble.exe"]  # list
  music_app = "chrome.exe"   # string
  unmute_on_quit = true      # bool
  
[keybindings]
  # all available keys can be found in readme.md
  # Do not use @ to represent shift->2
  # Instead, use toggle = '2' and toggle_mod = 'shift'
  toggle      = "caps_lock"
  toggle_mod  = ""           # ctrl, shift, alt, win, none, ""
  quit        = "f10"        # f12 seems to not work on windows 10
  quit_mod    = "none"
  suspend     = "f9"
  suspend_mod = "none"